# Generated by Django 5.0.6 on 2024-06-11 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('number', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stoppage',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_stop_time', models.TimeField()),
                ('next_stop_time', models.TimeField()),
                ('sequence', models.PositiveSmallIntegerField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.bus')),
                ('stoppage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.stoppage')),
            ],
            options={
                'ordering': ['bus', 'sequence'],
                'unique_together': {('bus', 'stoppage', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reverse_direction', models.BooleanField(default=False)),
                ('start_time', models.TimeField()),
                ('special', models.CharField(max_length=100)),
                ('days_of_week', models.PositiveSmallIntegerField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.bus')),
            ],
        ),
        migrations.CreateModel(
            name='LiveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.bus')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.route')),
                ('start_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.schedule')),
                ('stoppage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.stoppage')),
            ],
        ),
    ]
