# Generated by Django 5.0.6 on 2024-06-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_alter_schedule_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='special',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
