# Generated by Django 5.0.6 on 2024-06-11 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_alter_schedule_options_alter_stoppage_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='special',
            new_name='special_note',
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('bus', 'sequence')},
        ),
    ]
