# Generated by Django 5.0.6 on 2024-06-11 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_rename_special_schedule_special_note_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('bus', 'sequence'), ('bus', 'stoppage')},
        ),
    ]
