# Generated by Django 5.0.6 on 2024-06-11 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_alter_route_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('bus', 'sequence')},
        ),
    ]
