# Generated by Django 5.0.6 on 2024-06-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_alter_stoppage_latitude_alter_stoppage_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='special_note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
