# Generated by Django 5.0.6 on 2024-06-11 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_alter_schedule_days_of_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='special_note',
            new_name='special',
        ),
    ]
